### ISSUE TITLE
[Feature request?] Running certain checkers with their specific options

### ISSUE THREAD

**Issue by PawelLipski** [kelloggm/checkerframework-gradle-plugin#100]
Not sure if that's (easily) doable now as of 0.5.2... is it possible to pass a different set of options to each checker?

My specific case is that I'd like to pass different `-AqualDirs=...` to `SubtypingChecker` and different (actually, none) to `FenumChecker`. If I pass subtyping-specific `-AqualDirs=...` to `FenumChecker`, then `FenumChecker` screams about having two top types (one coming from my custom subtyping hierarchy, and the other one being `FenumTop`) :/ 

Possibly it's kinda indicates a bug in Checker itself, coz `FenumChecker` shouldn't (?) be interested in qualifiers outside of `FenumTop`-rooted hierarchy, even if they're passed via `-Aqual{s,Dirs}=...` :thinking:

**Comment by PawelLipski** [comment]
@kelloggm even more common use: an lint option (like `-Alint=redundantNullComparison`) only understood by single checker (e.g. `NullnessChecker`). Other checkers will warn if they see an unknown flag, and in case of `-Werror` this leads to build failure.

**Comment by smillst** [comment]
The Checker Framework supports this.  From [the manual](https://checkerframework.org/manual/#checker-options): 
>To pass an option to only a particular checker, prefix the option with the canonical or simple name of a checker, separated by an underscore “_”. Such an option will apply only to a checker with that name or any subclass of that checker. For example, you can use
```
-ANullnessChecker_lint=redundantNullComparison
-Aorg.checkerframework.checker.guieffect.GuiEffectChecker_lint=debugSpew
```

**Comment by PawelLipski** [comment]
Oh indeed, that's exactly what I was looking for, never came it across earlier though. Thanks!
