### ISSUE TITLE
Limit checked files to the ones modified according to Git history

### ISSUE THREAD

**Issue by vlsi** [kelloggm/checkerframework-gradle-plugin#111]
Use case: user modifies a couple of files, and they want to verify if there are checkerframework-detected issues.

Current behavior: checkerframework verifies all the files, and it takes significant time. For instance, pgjdbc compilation takes 4-6 minutes with CF enabled

Expected behavior: gradle-plugin could fetch the list of modified files (e.g. between origin/master and the current PR head), so checkerframework has much less classes/methods to verify.

**Comment by mernst** [comment]
This approach would save time, but it would not be sound -- that is, it could miss errors.

Suppose that a programmer changes class `Super`.  This might cause class `Sub` (a subclass of `Super`) to fail type-checking because an overriding relationship is no longer valid, or might cause `Client` (a client of `Super`) to fail type-checking because a call into `Super` is no longer valid.

**Comment by vlsi** [comment]
a) Can the checker figure out the relevant dependencies on its own?
b) CI can still verify all the classes (e.g. after the partial verification)
c) It would be nice if the checker could schedule "recently modified" files first, so the user can get the feedback faster.

What I mean here, is really sad to spend 4-6 minutes to figure out the way to put an annotation.

**Comment by mernst** [comment]
> a) Can the checker figure out the relevant dependencies on its own?

This isn't the place of the Checker Framework, but it would be possible to use an external tool.  Any tool that performs "impact analysis" should do the trick.  (And so may other tools that don't use that buzzword.)

> b) CI can still verify all the classes (e.g. after the partial verification)

I agree.

> c) It would be nice if the checker could schedule "recently modified" files first, so the user can get the feedback faster.

The Checker Framework does not do any scheduling.  javac does the scheduling, and the Checker Framework is merely an annotation processor that runs in the middle of the javac compilation.

Therefore, this workflow might address your concern:
 * change some files
 * run impact analysis to determine which files might contain a type-checking error (or, just use the modified files)
 * run javac on the subset of files, using the Checker Framework as an annotation processor
 * later (say, in CI), run javac on all the files, using the Checker Framework as an annotation processor

**Comment by mernst** [comment]
I'm closing this, because it seems to be the task of an external tool.  If anyone knows of a good tool that does the task, please comment.
