### ISSUE TITLE
Gradle Kotlin setup instructions?

### ISSUE THREAD

**Issue by nanodeath** [kelloggm/checkerframework-gradle-plugin#142]
Now that `build.gradle.kts` files are a thing, it'd be nice to have Kotlin-ified versions of examples in the readme, like this one:

```groovy
checkerFramework {
  checkers = [
    'org.checkerframework.checker.nullness.NullnessChecker',
    'org.checkerframework.checker.units.UnitsChecker'
  ]
}
```

I'm still experimenting and will let you know if I figure it out.

**Comment by nanodeath** [comment]
Alright, turns out this isn't rocket science. Following the guide [here](https://docs.gradle.org/nightly/userguide/migrating_from_groovy_to_kotlin_dsl.html#configuring-plugins) it looks like this is the answer:

```kotlin
configure<CheckerFrameworkExtension> {
    checkers = listOf(
        "org.checkerframework.checker.nullness.NullnessChecker",
        "org.checkerframework.checker.units.UnitsChecker"
    )
}
```

**Comment by mernst** [comment]
Thanks for the suggestion.  I have opened a pull request to update the instructions.
