### ISSUE TITLE
testFixtures

### ISSUE THREAD

**Issue by xenoterracide** [kelloggm/checkerframework-gradle-plugin#158]
add support and/or documentation for using the core `testFixtures` plugin with checkerframework.

**Comment by kelloggm** [comment]
Hi! I'd like to help, but I'm not sure what the problem actually is from your issue description. Did you encounter a problem when trying to use this plugin at the same time as `testFixtures`? If so, I'd love to see what went wrong! If you can post an example project that fails or an error trace, I might be able to help.

Theoretically, I don't see any reason that this plugin and `testFixtures` couldn't be used side-by-side without interfering with each other, though I've never tried to use both at the same time. By default, this plugin will be applied to any Java compilation tasks, which I think should include those provided by `java-test-fixtures`, so those sources will be checked by default. If you wanted to skip the test fixtures when running a checker, you could use the mechanism described [here](https://github.com/kelloggm/checkerframework-gradle-plugin#per-task-configuration) to skip the relevant compilation tasks.

**Comment by xenoterracide** [comment]
hmm... I'm going to close, but I thought the problem I noticed is that it wasn't being applied, however, I could be mistaken. Sorry for wasting your time. I'll reopen if I figure it out.
