### ISSUE TITLE
java.lang.UnsupportedOperationException: This iterator does not support removal

### ISSUE THREAD

**Issue by rgoldberg** [kelloggm/checkerframework-gradle-plugin#2]
> java.lang.UnsupportedOperationException: This iterator does not support removal

Thrown from `CheckerFrameworkPlugin#applyToTasks(…)` in newer versions of Gradle.

**Comment by mernst** [comment]
This issue related to the old implementation.
The plugin has been completely rewritten.
Could you please try again?  (Note that you will need to change your `build.gradle` file; see the [README file](https://github.com/kelloggm/checkerframework-gradle-plugin) for instructions.)
