### ISSUE TITLE
Updated instructions for JDK9+

### ISSUE THREAD

**Issue by entonio** [kelloggm/checkerframework-gradle-plugin#60]
Hi,
The current example to specify the CF version has the following:

    checkerFrameworkAnnotatedJDK 'org.checkerframework:jdk8:2.8.0'

I don't know how to adapt this to JDK 11 with CF 3.0.0, or if it's even needed.

**Comment by mernst** [comment]
That [section](https://github.com/kelloggm/checkerframework-gradle-plugin#specifying-a-checker-framework-version) starts with:

> This plugin uses Checker Framework version 3.0.0 by default. ... If you wish to use a specific Checker Framework version, add text like the following

Thus, if you want to use Checker framework version 3.0.0, you don't need to do anything special.

**Comment by entonio** [comment]
And it also says that tomorrow it will use a newer version by default. What do I do in order to continue using 3.0.0?

**Comment by mernst** [comment]
Version 0.4.9 of the plugin uses Checker Framework version 3.0.0 by default.
If you don't upgrade from version 0.4.9, then your build will continue to use Checker Framework version 3.0.0.
If you upgrade from version 0.4.9 of the plugin but still want to use Checker Framework version 3.0.0, you would add text including
```
...
checkerFrameworkAnnotatedJDK 'org.checkerframework:jdk8:3.0.0'
...
```
to your `build.gradle` file.

@entonio Does that make sense?  I updated the [README](https://github.com/kelloggm/checkerframework-gradle-plugin/tree/cf-version-default#specifying-a-checker-framework-version) to clarify this.  Can you let us know whether it is clear or still confusing?

@kelloggm Can you update the README so it gives instructions for both JDK8 and JDK11 (or indicate that it works for both)?

**Comment by entonio** [comment]
Hi,
My issue isn't so much with version C of the plugin using version Y of CF by default - I think that's good, and there is not much of an explanation needed other than no config is required.
However, if one does require a given CF version and JDK version, then I feel it should be explained how to configure them, if it's needed at all. 

For instance, if what I'm using is JDK11, then do I need that line with 'jdk8', or can I delete it, or do I have to use some other?

It's more or less clear to me that no config is needed so that the latest version of the plugin uses the latest version of CF (known to it) with JDK8 support. But what about latter JDKs?

We're in the process of migrating from Java 8 to 11 (because it's LTS and 14 isn't out yet), and the tooling we have to change is so much that when something breaks we have a hard time knowing where the problem is, or if there is a solution. We can't replace one component at a time because changing one requires changing the others (JDK / IDE / IDE plugins / gradle / CF), the versions of those have to be carefully combined due to all the Java 9 breakage.

I know CF is a lot of work with little thanks. I can only say you have my admiration. When I open an issue, it's really because I feel there is a slot for improvement.
