### ISSUE TITLE
project.afterEvaluated is deprecated since Gradle 5

### ISSUE THREAD

**Issue by eirnym** [kelloggm/checkerframework-gradle-plugin#81]
Hi, 

Gradle has [deprecated](https://docs.gradle.org/6.2.2/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated) project.afterEvaluated since Gradle 5 and it will be removed after Gradle 7

**Comment by kelloggm** [comment]
The link you posted does not say that all uses of `afterEvaluate` are deprecated, but rather that a subset of uses. Specifically, the linked text says

> Once a project is evaluated, Gradle ignores all configuration passed to Project#afterEvaluate and emits a deprecation warning. This scenario will become an error in Gradle 7.0

Have you encountered a deprecation warning of this kind from the plugin? If so, can you post a link to the project on which the deprecation warning is issued? The plugin should not be calling `afterEvaluate` on already-evaluated projects.
