### ISSUE TITLE
Please remove auto-applying the plugin to subprojects

### ISSUE THREAD

**Issue by vlsi** [kelloggm/checkerframework-gradle-plugin#88]
AFAIK, `applyToSubprojects` does not work since it defaults to `true`, and it is automatically applied to the subprojects as soon as the plugin is applied.

https://github.com/kelloggm/checkerframework-gradle-plugin/blob/51138478b760d9f183863f32a3a99be4e16354a1/src/main/groovy/org/checkerframework/gradle/plugin/CheckerFrameworkPlugin.groovy#L54-L74

Note: there's no way to configure `applyToSubprojects=false` because the extension does not exist before the plugin is applied.

**Comment by kelloggm** [comment]
Thanks for pointing this out. I've opened a PR with a fix: #91 

I also released a snapshot version that includes both that fix and #90, for your testing. That's version `0.5.0-SNAPSHOT`.

**Comment by vlsi** [comment]
@kelloggm , thanks, it looks like the issue is fixed.
